language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm run test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: K0sWJ1S6U+jg3sJEgqE5/mgpNO4fRcI4PwJJ5L0/uNskUriXuWz1EZ7NPnAEg1gz0kwU9a0eOy4DyDuycEg/EQC1gnAxpk7TKJYGv6+vbMs918T4nAl7GZHz6FK2/bEGLdhs5D86pTadT4pr1JVWWFNZdRFpBdasIVABN31OTKV4CI5gWwegQNBuKhEMhk0l2+n/AsUaBnEUf+wR0gXHJK0tSDJSBbj0V9li4biIQgGZSWuyfhTg7nYFwDPbYfzLmsEB5cOOqdd8oGIqfHBXXwvT3PnqEEs219y4K/y7CzTGJ/7Kx+z7i4BDeab1Z8zHUGvKkJNCNeQMafnQZ5+VJBxc4HY/SLJzNt++cdh/0SG9obm2liFZkmE7RjdrIPa2ic3xDTYSMmeefo/09QLVIOUBNAllvaUuTZW5jcPLjc1gdwAMk6v7V6rHZy+dnmE34jNfvKFQmdBg37gHFe1lnQZIhv6DhgyVEOg7wB1FduWgSpG72nchMpLG6R6ySY6ybdm6Fbaoe0Syit5Hy1yg6snZ2aCvtIiO4KahZZJkdfobXwXY96RQkQZO3z6o6twGyeAoPxJMRvgE9j3QQSgNNG/LngEmT5BwaotqTTsid0kMnRtwRzI1gE9A1FUecBOtOHH9WXGMSxx5XDoaNa7S4WvMvuKuXBvPvOM14+5LwXw=
  - secure: Oa2qrcavHutrkbsh+fFBgp3yZOJCuUogZ0puf0eXRMRbQWYAtgm0pBWpS1QbRWFXsn3udlJUTpqGdOHLU8U8nPH84qBcILIml9GKy1MtwLn/khepIT0fAUlo9x//nL+bqy0LzhaLRLr+e0A42iMT6oXblufv5yO64u3fGYbdMPWixHAJPgyXc6cdFfsU21JYMOIUSmHqAXH/A8tgc6nEV9z+3uKeHw8VT4UV9byFiLffDSPwlvGPfdZXnuGCoz7vnV8/Z5O5ifRnng89ciWhGjjIEpyMfKn+vvzg6iaEAvlsHvitmklmpF5jVVHGU3Jwwu+fCVVhRYkANeaa8MMrPLg21W74DUh0MuG5DVnG7JHA2ZRO5lKFDOF1cMWZQF6RXQvb3LS32g6mr5CI5TyUBylRmm4SZPwlp0Pr0nOVMGgiUzUmKcgYWO5U7Zxs5slG56Uk26g2igUoIz3EyYxe2Yd3c2zQFG6p0BTK7W36pKmnfvZt8AQS196uWL0DpOOEBolvX08I0GehpyZ2fyyeQ4kUfqCgZHt7v8hzkz9yyVVGbGlwd7fiHG8oyhJjO0Amh9JaqjtOdCdFxiFV/Lc0ZLPcDZ9fA2h65ky70m9f3j0q/sZriZ0h7z8qCVGfgAOPQWrpOrwmjydYEZjhFTTxE48G+bVlWp68E7DTkNOL7TM=
